.TH dump.exfat 8
.SH NAME
dump.exfat \- Show on-disk information of exfat filesystem
.SH SYNOPSIS
.B dump.exfat
[
.B \-d
.I file-path
]
.I device
.br
.B dump.exfat \-V
.SH DESCRIPTION
.B dump.exfat
Print on-disk information from given device that formatted by exFAT filesystem.

.PP
.SH OPTIONS
.TP
.B \-V
Prints the version number and exits.
.TP
.BR \-d ", " \-\-dentry-set=\fIpath\fR
Print information of directory entries from a given path that exits in the given device.
