name: Container Buildtests

# This workflow includes a make distcheck,
# thus we execute it also on most non-code changes
# to catch e.g. files missing in the generated
# make dist tarball.
on:
  push:
    branches:
      - master
      - exfat-next
    paths-ignore:
      - '**.md'
      - 'NEWS'
  pull_request:
    branches:
      - master
      - exfat-next
    paths-ignore:
      - '**.md'
      - 'NEWS'

jobs:
  container-build-alpine:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Packages
        run: |
          apk --update add \
            alpine-sdk autoconf libtool automake linux-headers bash xxd xz \
            util-linux-dev
      - name: Autoconf and Configure
        run: ./autogen.sh && ./configure
      - name: Distcheck
        run: make distcheck
      - name: Build
        run: make -j$((`nproc`+1))
      - name: Install
        run: make install
      - name: run fsck repair testcases
        run: |
          cd tests
          ./test_fsck.sh
  container-build-clang-lld:
    runs-on: ubuntu-latest
    container:
      image: debian:unstable
    steps:
      - uses: actions/checkout@v6
      - name: Install Packages
        run: |
          apt-get --update --quiet --yes install \
            clang lld pkgconf xxd autoconf \
            libtool automake make xz-utils libblkid-dev
      - name: Autoconf and Configure
        run: |
          export LDFLAGS="-fuse-ld=lld"
          ./autogen.sh && ./configure
      - name: Distcheck
        run: make distcheck
      - name: Build
        run:  make -j$((`nproc`+1))
      - name: Install
        run: make install
      - name: run fsck repair testcases
        run: |
          cd tests
          ./test_fsck.sh
